version: '3'
services:


  sqlserver:
    image: microsoft/mssql-server-linux:latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_PID=Developer
      - SA_PASSWORD=99888ukGh43hnDw89Hol8LN21112
   
      
  bookingapi:
    container_name: bookingapi
    image: bookingapi:latest   
    depends_on:      
      - sqlserver
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
      
  paymentapi:
    container_name: paymentapi
    image: paymentapi:latest   
    depends_on:      
      - sqlserver
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
      
  trackingapi:
    container_name: trackingapi
    image: trackingapi:latest   
    depends_on:      
      - sqlserver
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

      
  mcweb:
    container_name: mcweb
    image: mcweb:latest   
    depends_on:      
      - sqlserver
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
volumes:
  sqlserverdata:
    external: true    
