// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping.Persistence;

namespace Shipping.Persistence.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    partial class ShippingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shipping.Domain.Entities.Shippings", b =>
                {
                    b.Property<string>("ShippingsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookingOrderId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomerId");

                    b.Property<int>("ShippingStatus");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("ShippingsId");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("Shipping.Domain.Entities.ShippingsHistory", b =>
                {
                    b.Property<string>("ShippingsHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ShippingsId");

                    b.HasKey("ShippingsHistoryId");

                    b.HasIndex("ShippingsId");

                    b.ToTable("ShippingsHistory");
                });

            modelBuilder.Entity("Shipping.Domain.Entities.ShippingsHistory", b =>
                {
                    b.HasOne("Shipping.Domain.Entities.Shippings", "Shippings")
                        .WithMany("ShippingHistory")
                        .HasForeignKey("ShippingsId");
                });
#pragma warning restore 612, 618
        }
    }
}
